//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.SOAPHorario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPHorario.IHorario")]
    public interface IHorario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorario/fnObtenerHorario", ReplyAction="http://tempuri.org/IHorario/fnObtenerHorarioResponse")]
        SOAPServices.Dominio.Horario fnObtenerHorario(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorario/fnObtenerRangoHorario", ReplyAction="http://tempuri.org/IHorario/fnObtenerRangoHorarioResponse")]
        SOAPServices.Dominio.Horario[] fnObtenerRangoHorario();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHorarioChannel : ReservasWeb.SOAPHorario.IHorario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioClient : System.ServiceModel.ClientBase<ReservasWeb.SOAPHorario.IHorario>, ReservasWeb.SOAPHorario.IHorario {
        
        public HorarioClient() {
        }
        
        public HorarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Horario fnObtenerHorario(System.DateTime fecha) {
            return base.Channel.fnObtenerHorario(fecha);
        }
        
        public SOAPServices.Dominio.Horario[] fnObtenerRangoHorario() {
            return base.Channel.fnObtenerRangoHorario();
        }
    }
}
