//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.SOAPServiceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidomaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidopaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidomaterno {
            get {
                return this.apellidomaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidomaternoField, value) != true)) {
                    this.apellidomaternoField = value;
                    this.RaisePropertyChanged("apellidomaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidopaterno {
            get {
                return this.apellidopaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidopaternoField, value) != true)) {
                    this.apellidopaternoField = value;
                    this.RaisePropertyChanged("apellidopaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigocliente {
            get {
                return this.codigoclienteField;
            }
            set {
                if ((this.codigoclienteField.Equals(value) != true)) {
                    this.codigoclienteField = value;
                    this.RaisePropertyChanged("codigocliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccioncliente {
            get {
                return this.direccionclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionclienteField, value) != true)) {
                    this.direccionclienteField = value;
                    this.RaisePropertyChanged("direccioncliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dnicliente {
            get {
                return this.dniclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.dniclienteField, value) != true)) {
                    this.dniclienteField = value;
                    this.RaisePropertyChanged("dnicliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecliente {
            get {
                return this.nombreclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreclienteField, value) != true)) {
                    this.nombreclienteField = value;
                    this.RaisePropertyChanged("nombrecliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPServiceTest.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/RegistrarCliente", ReplyAction="http://tempuri.org/IClienteService/RegistrarClienteResponse")]
        TestProject.SOAPServiceTest.Cliente RegistrarCliente(int codigo, string dni, int tipo, string nombre, string apellidopaterno, string apellidomaterno, string correo, string direccion, string telefono, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObtenerCliente", ReplyAction="http://tempuri.org/IClienteService/ObtenerClienteResponse")]
        TestProject.SOAPServiceTest.Cliente ObtenerCliente(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ModificarCliente", ReplyAction="http://tempuri.org/IClienteService/ModificarClienteResponse")]
        TestProject.SOAPServiceTest.Cliente ModificarCliente(int codigo, string dni, int tipo, string nombre, string apellidopaterno, string apellidomaterno, string correo, string direccion, string telefono, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/Eliminar", ReplyAction="http://tempuri.org/IClienteService/EliminarResponse")]
        void Eliminar(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarCliente", ReplyAction="http://tempuri.org/IClienteService/ListarClienteResponse")]
        TestProject.SOAPServiceTest.Cliente[] ListarCliente();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : TestProject.SOAPServiceTest.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<TestProject.SOAPServiceTest.IClienteService>, TestProject.SOAPServiceTest.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestProject.SOAPServiceTest.Cliente RegistrarCliente(int codigo, string dni, int tipo, string nombre, string apellidopaterno, string apellidomaterno, string correo, string direccion, string telefono, string celular) {
            return base.Channel.RegistrarCliente(codigo, dni, tipo, nombre, apellidopaterno, apellidomaterno, correo, direccion, telefono, celular);
        }
        
        public TestProject.SOAPServiceTest.Cliente ObtenerCliente(int codigo) {
            return base.Channel.ObtenerCliente(codigo);
        }
        
        public TestProject.SOAPServiceTest.Cliente ModificarCliente(int codigo, string dni, int tipo, string nombre, string apellidopaterno, string apellidomaterno, string correo, string direccion, string telefono, string celular) {
            return base.Channel.ModificarCliente(codigo, dni, tipo, nombre, apellidopaterno, apellidomaterno, correo, direccion, telefono, celular);
        }
        
        public void Eliminar(int codigo) {
            base.Channel.Eliminar(codigo);
        }
        
        public TestProject.SOAPServiceTest.Cliente[] ListarCliente() {
            return base.Channel.ListarCliente();
        }
    }
}
