//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.SOAPVehiculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPVehiculo.IVehiculo")]
    public interface IVehiculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehiculo/fnObtenerVehiculo", ReplyAction="http://tempuri.org/IVehiculo/fnObtenerVehiculoResponse")]
        SOAPServices.Dominio.Vehiculo fnObtenerVehiculo(string placa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehiculoChannel : ReservasWeb.SOAPVehiculo.IVehiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculoClient : System.ServiceModel.ClientBase<ReservasWeb.SOAPVehiculo.IVehiculo>, ReservasWeb.SOAPVehiculo.IVehiculo {
        
        public VehiculoClient() {
        }
        
        public VehiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Vehiculo fnObtenerVehiculo(string placa) {
            return base.Channel.fnObtenerVehiculo(placa);
        }
    }
}
