//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.SOAPReservas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPReservas.IReserva")]
    public interface IReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/fnObtenerReserva", ReplyAction="http://tempuri.org/IReserva/fnObtenerReservaResponse")]
        SOAPServices.Dominio.Reserva fnObtenerReserva(int codReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/fnGuardarReserva", ReplyAction="http://tempuri.org/IReserva/fnGuardarReservaResponse")]
        SOAPServices.Dominio.Reserva fnGuardarReserva(SOAPServices.Dominio.Reserva objReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/fnListarReserva", ReplyAction="http://tempuri.org/IReserva/fnListarReservaResponse")]
        SOAPServices.Dominio.Reserva[] fnListarReserva(int codReserva, string nroReserva, string placa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaChannel : ReservasWeb.SOAPReservas.IReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaClient : System.ServiceModel.ClientBase<ReservasWeb.SOAPReservas.IReserva>, ReservasWeb.SOAPReservas.IReserva {
        
        public ReservaClient() {
        }
        
        public ReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Reserva fnObtenerReserva(int codReserva) {
            return base.Channel.fnObtenerReserva(codReserva);
        }
        
        public SOAPServices.Dominio.Reserva fnGuardarReserva(SOAPServices.Dominio.Reserva objReserva) {
            return base.Channel.fnGuardarReserva(objReserva);
        }
        
        public SOAPServices.Dominio.Reserva[] fnListarReserva(int codReserva, string nroReserva, string placa) {
            return base.Channel.fnListarReserva(codReserva, nroReserva, placa);
        }
    }
}
