//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.SOAPHorario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReservasWeb.SOAPHorario.HorarioBody[] horarioBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia1 {
            get {
                return this.dia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia1Field, value) != true)) {
                    this.dia1Field = value;
                    this.RaisePropertyChanged("dia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia2 {
            get {
                return this.dia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia2Field, value) != true)) {
                    this.dia2Field = value;
                    this.RaisePropertyChanged("dia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia3 {
            get {
                return this.dia3Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia3Field, value) != true)) {
                    this.dia3Field = value;
                    this.RaisePropertyChanged("dia3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia4 {
            get {
                return this.dia4Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia4Field, value) != true)) {
                    this.dia4Field = value;
                    this.RaisePropertyChanged("dia4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia5 {
            get {
                return this.dia5Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia5Field, value) != true)) {
                    this.dia5Field = value;
                    this.RaisePropertyChanged("dia5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia6 {
            get {
                return this.dia6Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia6Field, value) != true)) {
                    this.dia6Field = value;
                    this.RaisePropertyChanged("dia6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string header {
            get {
                return this.headerField;
            }
            set {
                if ((object.ReferenceEquals(this.headerField, value) != true)) {
                    this.headerField = value;
                    this.RaisePropertyChanged("header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReservasWeb.SOAPHorario.HorarioBody[] horarioBody {
            get {
                return this.horarioBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.horarioBodyField, value) != true)) {
                    this.horarioBodyField = value;
                    this.RaisePropertyChanged("horarioBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorarioBody", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class HorarioBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dia6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia1 {
            get {
                return this.dia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia1Field, value) != true)) {
                    this.dia1Field = value;
                    this.RaisePropertyChanged("dia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia2 {
            get {
                return this.dia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia2Field, value) != true)) {
                    this.dia2Field = value;
                    this.RaisePropertyChanged("dia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia3 {
            get {
                return this.dia3Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia3Field, value) != true)) {
                    this.dia3Field = value;
                    this.RaisePropertyChanged("dia3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia4 {
            get {
                return this.dia4Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia4Field, value) != true)) {
                    this.dia4Field = value;
                    this.RaisePropertyChanged("dia4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia5 {
            get {
                return this.dia5Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia5Field, value) != true)) {
                    this.dia5Field = value;
                    this.RaisePropertyChanged("dia5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dia6 {
            get {
                return this.dia6Field;
            }
            set {
                if ((object.ReferenceEquals(this.dia6Field, value) != true)) {
                    this.dia6Field = value;
                    this.RaisePropertyChanged("dia6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string header {
            get {
                return this.headerField;
            }
            set {
                if ((object.ReferenceEquals(this.headerField, value) != true)) {
                    this.headerField = value;
                    this.RaisePropertyChanged("header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPHorario.IHorario")]
    public interface IHorario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHorario/fnObtenerHorario", ReplyAction="http://tempuri.org/IHorario/fnObtenerHorarioResponse")]
        ReservasWeb.SOAPHorario.Horario fnObtenerHorario(System.DateTime fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHorarioChannel : ReservasWeb.SOAPHorario.IHorario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioClient : System.ServiceModel.ClientBase<ReservasWeb.SOAPHorario.IHorario>, ReservasWeb.SOAPHorario.IHorario {
        
        public HorarioClient() {
        }
        
        public HorarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReservasWeb.SOAPHorario.Horario fnObtenerHorario(System.DateTime fecha) {
            return base.Channel.fnObtenerHorario(fecha);
        }
    }
}
