//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.SOAPModelo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPModelo.IModelo")]
    public interface IModelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelo/fnObtenerModelo", ReplyAction="http://tempuri.org/IModelo/fnObtenerModeloResponse")]
        SOAPServices.Dominio.Modelo fnObtenerModelo(string codModelo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModeloChannel : ReservasWeb.SOAPModelo.IModelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModeloClient : System.ServiceModel.ClientBase<ReservasWeb.SOAPModelo.IModelo>, ReservasWeb.SOAPModelo.IModelo {
        
        public ModeloClient() {
        }
        
        public ModeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServices.Dominio.Modelo fnObtenerModelo(string codModelo) {
            return base.Channel.fnObtenerModelo(codModelo);
        }
    }
}
